modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/CookieBlock/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/CookieBlock/issues"

[[mods]]
	modId="cookieblock"
	version="${file.jarVersion}"
	displayName="Cookie Block"
	description='''A cookie block.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cookie-block"
	authors="bl4ckscor3"

[[dependencies.cookieblock]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookieblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"